global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'ihebmarnaoui@gmail.com'
  smtp_auth_username: 'ihebmarnaoui@gmail.com'
  smtp_auth_password: 'xxxxxxxxxxxx' #removed for security purposes
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 2m
  receiver: 'email-alert'  # default fallback

  routes:
    - match:
        alertname: OnPremDown
      receiver: 'webhook-failover'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'ihebmarnaoui@gmail.com'

  - name: 'webhook-failover'
    webhook_configs:
      - url: 'http://18.197.62.49:6000/failover'
