version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    depends_on:
      - alertmanager
      - haproxy-exporter
    networks:
      - monitoring-net

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/config.yml
    command:
    - "--config.file=/etc/alertmanager/config.yml"
    networks:
      - monitoring-net

  haproxy-exporter:
    image: prom/haproxy-exporter
    container_name: haproxy-exporter
    ports:
      - "9101:9101"
    command:
      - '--haproxy.scrape-uri=http://host.docker.internal:8404/stats;csv'
    networks:
      - monitoring-net


networks:
  monitoring-net:
    driver: bridge
