name: Deploy and Test Lifecycle

on:
  workflow_dispatch:

jobs:
  deploy-and-test:
    name: Provision EC2 and Test Lifecycle
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -var="key_name={{ secrets.SECRET_KEY }}" -auto-approve
